# SPDX-FileCopyrightText: 2021 Jeff Epler for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: 'Arduino CI'
description: 'Build code with arduino-ci'
inputs:
  repo-token:
    description: 'The github repository token, so that the deploy action can be run'
    reauired: true
    default: 'You must pass e.g., secrets.GH_REPO_TOKEN for this action to work. This means the action can perform github operations on your behalf, so ensure that it will only do actions you approve of'
  pretty-name:
    description: 'The pretty name of the repository'
    reauired: true
    default: '(set the pretty name in the actions .yml file)'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh
      shell: bash

    - name: test platforms
      run: python3 ci/build_platform.py main_platforms
      shell: bash

    - name: clang
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -r .
      shell: bash

    - name: doxygen
      env:
        GH_REPO_TOKEN: ${{ inputs.repo-token }}
        PRETTYNAME : ${{ inputs.pretty-name }}
      run: bash ci/doxy_gen_and_deploy.sh
      shell: bash

    - name: upload examples artifacts
      uses: actions/upload-artifact@v2
      with:
        name: examples hex files
        path: |
            examples/*/build/*/*.hex
